# Generated by Django 4.2.9 on 2024-12-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("height", models.CharField(max_length=10)),
                ("weight", models.CharField(max_length=10)),
                ("activity_level", models.CharField(max_length=20)),
                ("goal", models.CharField(max_length=20)),
                ("specific_goal", models.CharField(max_length=100)),
                ("medical_conditions", models.TextField(blank=True)),
                ("nutritional_needs", models.TextField(blank=True)),
                ("daily_diet", models.TextField(blank=True)),
                ("eating_out_frequency", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
